{% set name = "universaltest" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/device-servers/DeviceClasses/simulation/UniversalTest/-/releases/{{ version }}/downloads/UniversalTest-with-submodules-{{ version }}.tar.gz
  sha256: 8e37cd5f3823ec733b1ba6db9a1b4d0b7a0a8fbe7bfb885279befed345fa662a

build:
  number: 2

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - libtool                 # [unix]
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # UniversalTest --help returns 255, so grep the stderr for test
    - UniversalTest --help 2>&1 | grep usage         # [unix]
    - UniversalTest.exe --help 2>&1 | findstr usage  # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: UniversalTest Tango-Controls device server
  description: |
    A Tango device server able to create dynamic attributes of each Tango Type 
    and generating associated expert dynamic attributes to be able to change 
    the quality factor or behaviour of the other created attributes.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/device-servers/DeviceClasses/simulation/UniversalTest
  doc_url: https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-try-tango.html#play-with-tango-controls
  doc_source_url: https://gitlab.com/tango-controls/device-servers/DeviceClasses/simulation/UniversalTest/tree/main/README.md

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
