schema_version: 1

context:
  name: universaltest
  version: "1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/device-servers/DeviceClasses/simulation/UniversalTest/-/releases/${{ version }}/downloads/UniversalTest-with-submodules-${{ version }}.tar.gz
  sha256: 4ee03a2c5288f86de5f5c5c9b9c36a1c7d53e81dcfc634af828114fb157c2914

build:
  number: 0

requirements:
  build:
    - cmake
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - make
        - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

tests:
  - script:
      - if: unix
        then: UniversalTest --help 2>&1 | grep -i usage
      - if: win
        then: UniversalTest.exe --help 2>&1 | findstr /i usage

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: UniversalTest Tango-Controls device server
  description: |
    A Tango device server able to create dynamic attributes of each Tango Type
    and generating associated expert dynamic attributes to be able to change
    the quality factor or behaviour of the other created attributes.
    Tango-Controls is a software toolkit for building control systems.
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/device-servers/DeviceClasses/simulation/UniversalTest
  documentation: https://tango-controls.readthedocs.io

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
